### ISSUE TITLE
TypeError: '<' not supported between instances of 'NpzFile' and 'float'

### ISSUE THREAD

**Issue by colin-de** [robot-perception-group/GRADE_tools#2]
Hi, I found a issue when processing the file with ` ./process_data.sh -t file -p`
I got
```
./process_data.sh -t file -p /media/lwh/DATA/GRADE/FH/6fb8fb41/
TYPE : file
INPUT PATH : /media/lwh/DATA/GRADE/FH/6fb8fb41/
----------  Replicating IMU Data  ----------
----------  Replicating IMU Data  ----------
Traceback (most recent call last):
  File "/home/lwh/code/GRADE_tools/preprocessing/src/file_process/play_files.py", line 22, in <module>
    model.play_files()
  File "/home/lwh/code/GRADE_tools/preprocessing/src/file_process/add_noise.py", line 121, in play_files
    self.init_dir()
  File "/home/lwh/code/GRADE_tools/preprocessing/src/file_process/add_noise.py", line 61, in init_dir
    for f in os.listdir(self.imu_dirs[-1]):
FileNotFoundError: [Errno 2] No such file or directory: '/media/lwh/DATA/GRADE/FH/6fb8fb41/Viewport/imu_body'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
    import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
  File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

Original exception was:
Traceback (most recent call last):
  File "/home/lwh/code/GRADE_tools/preprocessing/src/file_process/play_files.py", line 22, in <module>
    model.play_files()
  File "/home/lwh/code/GRADE_tools/preprocessing/src/file_process/add_noise.py", line 121, in play_files
    self.init_dir()
  File "/home/lwh/code/GRADE_tools/preprocessing/src/file_process/add_noise.py", line 61, in init_dir
    for f in os.listdir(self.imu_dirs[-1]):
FileNotFoundError: [Errno 2] No such file or directory: '/media/lwh/DATA/GRADE/FH/6fb8fb41/Viewport/imu_body'
lwh@lwh-Dell:~/code/GRADE_tools/preprocessing(main)$ ./process_data.sh -t file -p /media/lwh/DATA/GRADE/FH/6fb8fb41/
TYPE : file
INPUT PATH : /media/lwh/DATA/GRADE/FH/6fb8fb41/
----------  Replicating IMU Data  ----------
----------  Replicating IMU Data  ----------
----------  Replicating RGB Data  ----------
----------  Replicating Depth Data  ----------
Depth Images Directory:  /media/lwh/DATA/GRADE/FH/6fb8fb41/data/depth

 ===============  PROCESSING VIEWPORT  ===============


 ===============  Generating non-noisy Depth Images  ===============
Traceback (most recent call last):
  File "/home/lwh/code/GRADE_tools/preprocessing/src/file_process/play_files.py", line 22, in <module>
    model.play_files()
  File "/home/lwh/code/GRADE_tools/preprocessing/src/file_process/add_noise.py", line 137, in play_files
    self.save_image(fn, depth)
  File "/home/lwh/code/GRADE_tools/preprocessing/src/file_process/add_noise.py", line 150, in save_image
    mask = np.logical_or((depth < self.MIN_DEPTH),(depth > self.MAX_DEPTH))
TypeError: '<' not supported between instances of 'NpzFile' and 'float'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
    import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
  File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

Original exception was:
Traceback (most recent call last):
  File "/home/lwh/code/GRADE_tools/preprocessing/src/file_process/play_files.py", line 22, in <module>
    model.play_files()
  File "/home/lwh/code/GRADE_tools/preprocessing/src/file_process/add_noise.py", line 137, in play_files
    self.save_image(fn, depth)
  File "/home/lwh/code/GRADE_tools/preprocessing/src/file_process/add_noise.py", line 150, in save_image
    mask = np.logical_or((depth < self.MIN_DEPTH),(depth > self.MAX_DEPTH))
TypeError: '<' not supported between instances of 'NpzFile' and 'float'
lwh@lwh-Dell:~/code/GRADE_tools/preprocessing(main)$ ./process_data.sh -t file -p /media/lwh/DATA/GRADE/FH/6fb8fb41/
TYPE : file
INPUT PATH : /media/lwh/DATA/GRADE/FH/6fb8fb41/
----------  Replicating IMU Data  ----------
----------  Replicating IMU Data  ----------
----------  Replicating RGB Data  ----------
----------  Replicating Depth Data  ----------
Depth Images Directory:  /media/lwh/DATA/GRADE/FH/6fb8fb41/data/depth

 ===============  PROCESSING VIEWPORT  ===============


 ===============  Generating non-noisy Depth Images  ===============
Traceback (most recent call last):
  File "/home/lwh/code/GRADE_tools/preprocessing/src/file_process/play_files.py", line 22, in <module>
    model.play_files()
  File "/home/lwh/code/GRADE_tools/preprocessing/src/file_process/add_noise.py", line 137, in play_files
    self.save_image(fn, depth)
  File "/home/lwh/code/GRADE_tools/preprocessing/src/file_process/add_noise.py", line 149, in save_image
    mask = np.logical_or((depth < self.MIN_DEPTH),(depth > self.MAX_DEPTH))
TypeError: '<' not supported between instances of 'NpzFile' and 'float'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
    import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
  File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

Original exception was:
Traceback (most recent call last):
  File "/home/lwh/code/GRADE_tools/preprocessing/src/file_process/play_files.py", line 22, in <module>
    model.play_files()
  File "/home/lwh/code/GRADE_tools/preprocessing/src/file_process/add_noise.py", line 137, in play_files
    self.save_image(fn, depth)
  File "/home/lwh/code/GRADE_tools/preprocessing/src/file_process/add_noise.py", line 149, in save_image
    mask = np.logical_or((depth < self.MIN_DEPTH),(depth > self.MAX_DEPTH))
TypeError: '<' not supported between instances of 'NpzFile' and 'float'
```

**Comment by colin-de** [comment]
the key was missing and a potential solution could be 
add a line `depth = depth['arr_0']`

**Comment by eliabntt** [comment]
Yes, we assume npy files. npz was chosen to compress the data.
